### PR TITLE
fix `close(::Figure)` and add test

### LINKED ISSUE #22: `close(::Figure)` still broken
@stevengj The fix for #21 didn't work I'm afraid.

On main https://github.com/stevengj/PythonPlot.jl/commit/cc633dd2536513736bfaea4c47a1da86e25549fb
```
julia> f = PythonPlot.figure(figsize = (6, 6), dpi = 100)
Figure(<py Figure size 600x600 with 0 Axes>)

julia> close(f)
ERROR: cannot convert this Python 'NoneType' to a Julia 'Int64'
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] macro expansion
   @ ~/.julia/packages/PythonCall/dsECZ/src/convert.jl:355 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/PythonCall/dsECZ/src/Py.jl:131 [inlined]
 [4] pyconvert(#unused#::Type{Int64}, x::PythonCall.Py)
   @ PythonCall ~/.julia/packages/PythonCall/dsECZ/src/convert.jl:370
 [5] plotclose(f::Figure)
   @ PythonPlot ~/.julia/packages/PythonPlot/oPo8Q/src/PythonPlot.jl:193
 [6] close(f::Figure)
   @ PythonPlot ~/.julia/packages/PythonPlot/oPo8Q/src/PythonPlot.jl:189
 [7] top-level scope
   @ REPL[4]:1
```

It would've been good for the fix to be made in a PR with a test added.

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes #22

### CODE REVIEW

File: src/PythonPlot.jl [hunk 1]
```diff
@@ -190,7 +190,7 @@ Base.close(f::Figure) = plotclose(f)
 
 # rename to avoid type piracy:
 @doc LazyHelp(pyplot,"close") plotclose() = pyplot.close()
-plotclose(f::Figure) = pyconvert(Int, plotclose(pyconvert(Int, f.number)))
+plotclose(f::Figure) = pyconvert(Union{Nothing,Int}, plotclose(pyconvert(Int, f.number)))
```
Comment (stevengj) [inline src/PythonPlot.jl:193]: It looks like we can just close the figure object directly nowadays, rather than getting `f.number` first:
```suggestion
plotclose(f::Figure) = pyplot.close(f)
```

Comment (stevengj) [reply src/PythonPlot.jl:193]: Oh, but we track it in `withfig_fignums`.
